refactor: use @scaleway/ui own types
scaleway/scaleway-ui-website pull request #217
Opened 2021-11-04 16:36 UTC by chambo-e

## Summary

Needs https://github.com/scaleway/scaleway-ui/pull/878/files to be published first

## Type

- Refactor

2021-11-07 21:09 UTC, vincentaudebert requested changes
lint a pas l'air heureux avec tes changements @chambo-e ?

2021-11-08 09:23 UTC, chambo-e commented
> lint a pas l'air heureux avec tes changements @chambo-e ?

Corrected :)

2021-11-08 11:48 UTC, vincentaudebert approved these changes

2021-11-08 13:18 UTC, matthprost approved these changes

2021-11-08 13:24 UTC, merged