Draft: fix: some site structure changes
scaleway/scaleway-ui-website pull request #223
Opened 2021-11-08 18:13 UTC by vincentaudebert

## Summary

## Type

- Bug
- Feature
- Enhancement
- Documentation
- Migration
- Refactor

### Summarise concisely:

#### What is expected?

(Description of the new behavior)

#### The following changes where made:

(Describe what you did)

1.

2.

3.

## Relevant logs and/or screenshots

Page | Before | After
:-   |  :-:   | -:
url | screenshot | screenshot
url | screenshot | screenshot

2021-11-09 18:08 UTC, vincentaudebert commented
What icons do we need:

- Icons for Introduction blocks (Accessibility, Customizable, DevXP)
- Icons for Open source libs
- Better Slack/community icon?
- Why is the illustration a man? Should we be more inclusive?

2021-11-10 12:03 UTC, matthprost requested changes
https://user-images.githubusercontent.com/15812968/141109707-44ca8e97-9f15-49f0-baab-fe1362a7c983.mov

Copy / paste button is broken on getting started 🤔

2021-11-10 12:04 UTC, matthprost requested changes

2021-11-10 12:04 UTC, matthprost commented on src/pages/home/GettingStarted.tsx
> +          <CopyBox.Command title="Install" command={install} />
I think we should add code snippet for npm too

2021-11-15 09:19 UTC, matthprost commented
Seems like dark / light mode doesn't work anymore on this PR

2021-11-15 09:23 UTC, matthprost requested changes

2021-11-15 09:23 UTC, matthprost commented on src/pages/home/GettingStarted.tsx
> +            <CopyBox.Command title="Install" command={installNpm} />
Can you change `CopyBox.Command` props to be able to receive `showLineNumbers` as prop and pass it to `SyntaxHighlighter` ?

Then here you could hide line number as it is just a one line command, and make it true by default

2021-11-15 09:24 UTC, matthprost requested changes

2021-11-15 09:24 UTC, matthprost commented on src/pages/home/index.tsx
> +      <Button size="large">Join the Community Slack</Button>
No link to the slack community ?

2021-11-15 09:56 UTC, vincentaudebert commented on src/pages/home/index.tsx
> +      <Button size="large">Join the Community Slack</Button>
Not yet, @philibea was meant to create it and give it to me. I will ask.

2021-11-15 10:14 UTC, philibea commented on src/pages/home/index.tsx
> +      <Button size="large">Join the Community Slack</Button>
Created @vincentaudebert

2021-11-16 08:58 UTC, matthprost approved these changes

2021-11-16 10:20 UTC, chambo-e commented on src/components/CopyBoxCommand.tsx
> +CopyBox.defaultProps = {
Not needed :)

You can disable the rule for tsx files if you want :)

2021-11-16 15:27 UTC, merged